"""
Flow    : TEST_188001_MemberLogin
Source  : TEST_188001_MEMBER_LOGIN.qfl

AUTO-GENERATED by tools/qfl_to_pyautogui.py
Search for  # TODO  and resolve every item before running in CI.

Conversion Report
  Statements   : 23
  Score        : 94%  → EXCELLENT
  EXACT        :  19  (83%)
  GOOD         :   3  (13%)
  LOW          :   1  (4%)
  TODOs to fix : 4  (search '# TODO' below)
"""

from __future__ import annotations

from automation.common import Context
from automation.common.data import DataRow
from automation.core import actions, ocr, waits


def _screen_exists(or_repo, anchor: str, *, timeout: float) -> bool:
    """Return True if the anchor element appears within timeout, False otherwise."""
    try:
        waits.wait_for_object_exists(or_repo.get(anchor), timeout=timeout)
        return True
    except Exception:
        return False


def flow_test_188001_member_login(ctx: Context, row: DataRow) -> None:
    """Execute TEST_188001_MemberLogin."""
    or_repo = ctx.or_repo

    # ── Load data from CSV row ───────────────────────────────────
    username = row.require("Username")
    password = row.require("Password")
    expected_title = row.require("ExpectedTitle")


    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "epic_login.header_label", timeout=15):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 1", "Epic login screen did not appear within 15 seconds")
        raise AssertionError("Step 1 failed")
    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("Step 1", "Epic login screen is visible")

    # confidence: EXACT (100) - WebEdit.Set
    actions.type_text("member_login.username", username)
    # confidence: GOOD (75) - Wait 1
    # TODO: Wait 1 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - WebEdit.Set
    actions.type_text("member_login.password", password)
    # confidence: GOOD (75) - Wait 1
    # TODO: Wait 1 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - WebButton.Click
    actions.click("member_login.sign_in")
    # confidence: GOOD (75) - Wait 3
    # TODO: Wait 3 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "epic_home.header_label", timeout=20):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 5", "Epic home screen did not load after login")
        raise AssertionError("Step 5 failed")

    # confidence: LOW (30) - Browser.Page.GetROProperty(title)
    # TODO: get page/window title — use pygetwindow or OCR on title bar
    # import pygetwindow as gw; actual_title = gw.getActiveWindow().title
    actual_title = "TODO_window_title"
    # confidence: EXACT (100) - If...Then block
    if not (expected_title in actual_title):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 6", "Title mismatch. Expected: " + expected_title + " Got: " + actual_title)
        raise AssertionError("Step 6 failed")

    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("TEST_188001_MemberLogin", "Login successful for user: " + username)


