"""
Flow    : TEST_188003_CoverageVerify
Source  : TEST_188003_COVERAGE_VERIFY.qfl

AUTO-GENERATED by tools/qfl_to_pyautogui.py
Search for  # TODO  and resolve every item before running in CI.

Conversion Report
  Statements   : 31
  Score        : 98%  → EXCELLENT
  EXACT        :  27  (87%)
  HIGH         :   3  (10%)
  GOOD         :   1  (3%)
  TODOs to fix : 1  (search '# TODO' below)
"""

from __future__ import annotations

from automation.common import Context
from automation.common.data import DataRow
from automation.core import actions, ocr, waits


def _screen_exists(or_repo, anchor: str, *, timeout: float) -> bool:
    """Return True if the anchor element appears within timeout, False otherwise."""
    try:
        waits.wait_for_object_exists(or_repo.get(anchor), timeout=timeout)
        return True
    except Exception:
        return False


def flow_test_188003_coverage_verify(ctx: Context, row: DataRow) -> None:
    """Execute TEST_188003_CoverageVerify."""
    or_repo = ctx.or_repo

    # ── Load data from CSV row ───────────────────────────────────
    coverage_effective_date = row.require("CoverageEffectiveDate")
    expected_plan_name = row.require("PlanName")
    expected_status = row.require("ExpectedStatus")


    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "member_chart.header_label", timeout=10):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 1", "Member chart is not open")
        raise AssertionError("Step 1 failed")

    # confidence: EXACT (100) - WebElement.Click
    actions.click("coverage_verify.coverage_tab")
    # confidence: GOOD (75) - Wait 2
    # TODO: Wait 2 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "coverage_section.header_label", timeout=10):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 3", "Coverage section did not load")
        raise AssertionError("Step 3 failed")
    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("Step 3", "Coverage section loaded")

    # confidence: HIGH (90) - Browser.Page.WebElement.GetROProperty
    actual_date_result = ocr.read_target("coverage_verify.effective_date_field_text")
    actual_date = actual_date_result.text
    # confidence: EXACT (100) - If...Then block
    if actual_date != coverage_effective_date:
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 4", "Effective date mismatch. Expected: " + coverage_effective_date + " Got: " + actual_date)
        raise AssertionError("Step 4 failed")
    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("Step 4", "Effective date verified: " + actual_date)

    # confidence: HIGH (90) - Browser.Page.WebElement.GetROProperty
    actual_plan_result = ocr.read_target("coverage_verify.plan_name_field_text")
    actual_plan = actual_plan_result.text
    # confidence: EXACT (100) - If...Then block
    if not (expected_plan_name in actual_plan):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 5", "Plan name mismatch. Expected: " + expected_plan_name + " Got: " + actual_plan)
        raise AssertionError("Step 5 failed")
    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("Step 5", "Plan name verified: " + actual_plan)

    # confidence: HIGH (90) - Browser.Page.WebElement.GetROProperty
    actual_status_result = ocr.read_target("coverage_verify.coverage_status_field_text")
    actual_status = actual_status_result.text
    # confidence: EXACT (100) - If...Then block
    if not (expected_status in actual_status):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 6", "Status mismatch. Expected: " + expected_status + " Got: " + actual_status)
        raise AssertionError("Step 6 failed")

    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("TEST_188003_CoverageVerify", "Coverage verified. Plan: " + actual_plan + " Effective: " + actual_date + " Status: " + actual_status)


