"""
Flow    : TEST_188002_MemberSearch
Source  : TEST_188002_MEMBER_SEARCH.qfl

AUTO-GENERATED by tools/qfl_to_pyautogui.py
Search for  # TODO  and resolve every item before running in CI.

Conversion Report
  Statements   : 34
  Score        : 97%  → EXCELLENT
  EXACT        :  29  (85%)
  HIGH         :   1  (3%)
  GOOD         :   4  (12%)
  TODOs to fix : 4  (search '# TODO' below)
"""

from __future__ import annotations

from automation.common import Context
from automation.common.data import DataRow
from automation.core import actions, ocr, waits


def _screen_exists(or_repo, anchor: str, *, timeout: float) -> bool:
    """Return True if the anchor element appears within timeout, False otherwise."""
    try:
        waits.wait_for_object_exists(or_repo.get(anchor), timeout=timeout)
        return True
    except Exception:
        return False


def flow_test_188002_member_search(ctx: Context, row: DataRow) -> None:
    """Execute TEST_188002_MemberSearch."""
    or_repo = ctx.or_repo

    # ── Load data from CSV row ───────────────────────────────────
    mrn = row.require("MemberID")
    last_name = row.require("LastName")
    first_name = row.require("FirstName")
    date_of_birth = row.require("DateOfBirth")


    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "epic_home.header_label", timeout=10):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 1", "Epic home screen not visible")
        raise AssertionError("Step 1 failed")
    # confidence: EXACT (100) - WebElement.Click
    actions.click("member_search.patient_search_bar")
    # confidence: GOOD (75) - Wait 1
    # TODO: Wait 1 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - WebEdit.Set
    actions.type_text("member_search.mrn_search_input", mrn)
    # confidence: GOOD (75) - Wait 1
    # TODO: Wait 1 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - WebButton.Click
    actions.click("member_search.search_button")
    # confidence: GOOD (75) - Wait 2
    # TODO: Wait 2 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "search_results.header_label", timeout=10):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 4", "Search results did not load for MRN: " + mrn)
        raise AssertionError("Step 4 failed")

    # confidence: EXACT (100) - WebElement.Click
    actions.click("member_search.first_result_row")
    # confidence: GOOD (75) - Wait 2
    # TODO: Wait 2 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "member_chart.header_label", timeout=15):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 6", "Member chart did not open")
        raise AssertionError("Step 6 failed")

    # confidence: HIGH (90) - Browser.Page.WebElement.GetROProperty
    banner_text_result = ocr.read_target("member_search.patient_banner_text")
    banner_text = banner_text_result.text
    # confidence: EXACT (100) - If...Then block
    if not (last_name in banner_text):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 7", "Last name not found in banner. Banner: " + banner_text)
        raise AssertionError("Step 7 failed")
    # confidence: EXACT (100) - If...Then block
    if not (first_name in banner_text):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 7", "First name not found in banner. Banner: " + banner_text)
        raise AssertionError("Step 7 failed")

    # confidence: EXACT (100) - If...Then block
    if not (date_of_birth in banner_text):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 8", "DOB not found in banner. Expected: " + date_of_birth)
        raise AssertionError("Step 8 failed")

    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("TEST_188002_MemberSearch", "Member found and verified: " + first_name + " " + last_name + " MRN: " + mrn)


