"""
Flow    : TEST_188004_NewEnrollment
Source  : TEST_188004_NEW_ENROLLMENT.qfl

AUTO-GENERATED by tools/qfl_to_pyautogui.py
Search for  # TODO  and resolve every item before running in CI.

Conversion Report
  Statements   : 40
  Score        : 94%  → EXCELLENT
  EXACT        :  31  (78%)
  HIGH         :   1  (2%)
  GOOD         :   6  (15%)
  MEDIUM       :   2  (5%)
  TODOs to fix : 8  (search '# TODO' below)
"""

from __future__ import annotations

from automation.common import Context
from automation.common.data import DataRow
from automation.core import actions, ocr, waits


def _screen_exists(or_repo, anchor: str, *, timeout: float) -> bool:
    """Return True if the anchor element appears within timeout, False otherwise."""
    try:
        waits.wait_for_object_exists(or_repo.get(anchor), timeout=timeout)
        return True
    except Exception:
        return False


def flow_test_188004_new_enrollment(ctx: Context, row: DataRow) -> None:
    """Execute TEST_188004_NewEnrollment."""
    or_repo = ctx.or_repo

    # ── Load data from CSV row ───────────────────────────────────
    member_id = row.require("MemberID")
    plan_code = row.require("PlanCode")
    effective_date = row.require("EffectiveDate")
    enrollment_type = row.require("EnrollmentType")


    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "member_chart.header_label", timeout=10):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 1", "Member chart not open for MRN: " + member_id)
        raise AssertionError("Step 1 failed")

    # confidence: EXACT (100) - WebElement.Click
    actions.click("new_enrollment.activity_menu")
    # confidence: GOOD (75) - Wait 1
    # TODO: Wait 1 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))
    # confidence: EXACT (100) - WebElement.Click
    actions.click("new_enrollment.enrollment_menu_item")
    # confidence: GOOD (75) - Wait 2
    # TODO: Wait 2 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "enrollment_panel.header_label", timeout=15):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 3", "Enrollment panel did not open")
        raise AssertionError("Step 3 failed")
    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("Step 3", "Enrollment panel loaded")

    # confidence: MEDIUM (55) - WebList.Select
    # TODO: dropdown select — click to open, then locate option by OCR
    actions.click("new_enrollment.enrollment_type_dropdown")
    actions.type_text("new_enrollment.enrollment_type_dropdown", enrollment_type)  # or use arrow-key navigation
    # confidence: GOOD (75) - Wait 1
    # TODO: Wait 1 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: MEDIUM (55) - WebList.Select
    # TODO: dropdown select — click to open, then locate option by OCR
    actions.click("new_enrollment.plan_dropdown")
    actions.type_text("new_enrollment.plan_dropdown", plan_code)  # or use arrow-key navigation
    # confidence: GOOD (75) - Wait 1
    # TODO: Wait 1 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))
    # confidence: EXACT (100) - If...Then block
    if ocr.read_target("new_enrollment.plan_dropdown_text").text != plan_code:
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 5", "Plan selection failed for code: " + plan_code)
        raise AssertionError("Step 5 failed")
    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("Step 5", "Plan selected: " + plan_code)

    # confidence: EXACT (100) - WebEdit.Set
    actions.type_text("new_enrollment.effective_date_input", effective_date)
    # confidence: GOOD (75) - Wait 1
    # TODO: Wait 1 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - If...Then block
    if _screen_exists(or_repo, "new_enrollment.date_validation_error", timeout=2):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 7", "Date validation error shown for: " + effective_date)
        raise AssertionError("Step 7 failed")

    # confidence: EXACT (100) - WebButton.Click
    actions.click("new_enrollment.submit_enrollment")
    # confidence: GOOD (75) - Wait 3
    # TODO: Wait 3 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "confirmation_page.header_label", timeout=15):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 9", "Confirmation page did not appear after submit")
        raise AssertionError("Step 9 failed")

    # confidence: HIGH (90) - Browser.Page.WebElement.GetROProperty
    confirm_text_result = ocr.read_target("new_enrollment.confirmation_message_text")
    confirm_text = confirm_text_result.text
    # confidence: EXACT (100) - If...Then block
    if not ("successfully" in confirm_text):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 9", "Enrollment not confirmed. Message: " + confirm_text)
        raise AssertionError("Step 9 failed")

    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("TEST_188004_NewEnrollment", "Enrollment submitted. MemberID: " + member_id + " Plan: " + plan_code + " Effective: " + effective_date)


