"""
Flow    : TEST_188005_CoverageChange
Source  : TEST_188005_COVERAGE_CHANGE.qfl

AUTO-GENERATED by tools/qfl_to_pyautogui.py
Search for  # TODO  and resolve every item before running in CI.

Conversion Report
  Statements   : 51
  Score        : 94%  → EXCELLENT
  EXACT        :  39  (76%)
  HIGH         :   3  (6%)
  GOOD         :   7  (14%)
  MEDIUM       :   2  (4%)
  TODOs to fix : 9  (search '# TODO' below)
"""

from __future__ import annotations

from automation.common import Context
from automation.common.data import DataRow
from automation.core import actions, ocr, waits


def _screen_exists(or_repo, anchor: str, *, timeout: float) -> bool:
    """Return True if the anchor element appears within timeout, False otherwise."""
    try:
        waits.wait_for_object_exists(or_repo.get(anchor), timeout=timeout)
        return True
    except Exception:
        return False


def flow_test_188005_coverage_change(ctx: Context, row: DataRow) -> None:
    """Execute TEST_188005_CoverageChange."""
    or_repo = ctx.or_repo

    # ── Load data from CSV row ───────────────────────────────────
    member_id = row.require("MemberID")
    old_plan_code = row.require("OldPlanCode")
    new_plan_code = row.require("NewPlanCode")
    change_effective_date = row.require("ChangeEffectiveDate")
    change_reason = row.require("ChangeReason")


    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "member_chart.header_label", timeout=10):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 1", "Member chart not open. MRN: " + member_id)
        raise AssertionError("Step 1 failed")

    # confidence: EXACT (100) - WebElement.Click
    actions.click("coverage_change.coverage_tab")
    # confidence: GOOD (75) - Wait 2
    # TODO: Wait 2 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))
    # confidence: HIGH (90) - Browser.Page.WebElement.GetROProperty
    current_plan_result = ocr.read_target("coverage_change.plan_name_field_text")
    current_plan = current_plan_result.text
    # confidence: EXACT (100) - If...Then block
    if not (old_plan_code in current_plan):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 2", "Current plan is not the expected old plan. Got: " + current_plan)
        raise AssertionError("Step 2 failed")
    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("Step 2", "Current plan confirmed: " + current_plan)

    # confidence: EXACT (100) - WebElement.Click
    actions.click("coverage_change.activity_menu")
    # confidence: GOOD (75) - Wait 1
    # TODO: Wait 1 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))
    # confidence: EXACT (100) - WebElement.Click
    actions.click("coverage_change.coverage_change_menu_item")
    # confidence: GOOD (75) - Wait 2
    # TODO: Wait 2 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "coverage_change_dialog.header_label", timeout=15):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 4", "Coverage change dialog did not open")
        raise AssertionError("Step 4 failed")
    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("Step 4", "Coverage change dialog is open")

    # confidence: MEDIUM (55) - WebList.Select
    # TODO: dropdown select — click to open, then locate option by OCR
    actions.click("coverage_change.change_reason_dropdown")
    actions.type_text("coverage_change.change_reason_dropdown", change_reason)  # or use arrow-key navigation
    # confidence: GOOD (75) - Wait 1
    # TODO: Wait 1 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: MEDIUM (55) - WebList.Select
    # TODO: dropdown select — click to open, then locate option by OCR
    actions.click("coverage_change.new_plan_dropdown")
    actions.type_text("coverage_change.new_plan_dropdown", new_plan_code)  # or use arrow-key navigation
    # confidence: GOOD (75) - Wait 1
    # TODO: Wait 1 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))
    # confidence: EXACT (100) - If...Then block
    if ocr.read_target("coverage_change.new_plan_dropdown_text").text != new_plan_code:
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 6", "New plan selection failed: " + new_plan_code)
        raise AssertionError("Step 6 failed")

    # confidence: EXACT (100) - WebEdit.Set
    actions.type_text("coverage_change.change_effective_date_input", change_effective_date)
    # confidence: GOOD (75) - Wait 1
    # TODO: Wait 1 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - If...Then block
    if _screen_exists(or_repo, "coverage_change.effective_date_rule_error", timeout=3):
        # confidence: HIGH (90) - Browser.Page.WebElement.GetROProperty
        rule_error_result = ocr.read_target("coverage_change.effective_date_rule_error_text")
        rule_error = rule_error_result.text
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 8", "Effective date rule violation: " + rule_error)
        raise AssertionError("Step 8 failed")
    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("Step 8", "Effective date accepted: " + change_effective_date)

    # confidence: EXACT (100) - WebButton.Click
    actions.click("coverage_change.accept_change")
    # confidence: GOOD (75) - Wait 3
    # TODO: Wait 3 — replace with:
    # waits.wait_for_screen_stable(region=(0, 0, 1280, 800))

    # confidence: EXACT (100) - If...Then block
    if not _screen_exists(or_repo, "coverage_section.header_label", timeout=15):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 10", "Coverage section did not refresh after change")
        raise AssertionError("Step 10 failed")

    # confidence: HIGH (90) - Browser.Page.WebElement.GetROProperty
    updated_plan_result = ocr.read_target("coverage_change.plan_name_field_text")
    updated_plan = updated_plan_result.text
    # confidence: EXACT (100) - If...Then block
    if not (new_plan_code in updated_plan):
        # confidence: EXACT (100) - Reporter micFail
        ctx.reporter.failed("Step 10", "Coverage change not reflected. Got plan: " + updated_plan)
        raise AssertionError("Step 10 failed")

    # confidence: EXACT (100) - Reporter micPass
    ctx.reporter.passed("TEST_188005_CoverageChange", "Coverage changed. MRN: " + member_id + " Old: " + old_plan_code + " New: " + new_plan_code + " Effective: " + change_effective_date)


